// bottom_panel/Kartor/Oversattningstabell_kartor.js
var translationTable = {
    "lan_namn": "Län Namn",
    "blasand__1": "Bläsand",
    "blasand_aj": "Jakttid",
    "blasand_kl": "Jakt under dygnet",
    "blasand_ka": "Kaliberkrav",
    "blasgas__1": "Bläsgås",
    "blasgas_aj": "Jakttid",
    "blasgas_kl": "Jakt under dygnet",
    "blasgas_ka": "Kaliberkrav",
    "dalripa__1": "Dalripa",
    "dalripa_aj": "Jakttid",
    "dalripa_kl": "Jakt under dygnet",
    "dalripa_ka": "Kaliberkrav",
    "fasan_ajt": "Fasan",
    "fasan_ajf": "Jakttid",
    "fasan_kloc": "Jakt under dygnet",
    "fasan_kali": "Kaliberkrav",
    "fiskmas__1": "Fiskmås",
    "fiskmas_aj": "Jakttid",
    "fiskmas_kl": "Jakt under dygnet",
    "fiskmas_ka": "Kaliberkrav",
    "fjallripa1": "Fjällripa",
    "fjallripa_": "Jakttid",
    "fjallrip_1": "Jakt under dygnet",
    "fjallrip_2": "Kaliberkrav",
    "gragas_ajt": "Grågås",
    "gragas_ajf": "Jakttid",
    "gragas_klo": "Jakt under dygnet",
    "gragas_kal": "Kaliberkrav",
    "gratrut__1": "Gråtrut",
    "gratrut_aj": "Jakttid",
    "gratrut_kl": "Jakt under dygnet",
    "gratrut_ka": "Kaliberkrav",
    "grasand__1": "Gräsand",
    "grasand_aj": "Jakttid",
    "grasand_kl": "Jakt under dygnet",
    "grasand_ka": "Kaliberkrav",
    "jarpe_info": "Järpe",
    "jarpe_ajf": "Jakttid",
    "jarpe_kloc": "Jakt under dygnet",
    "jarpe_kali": "Kaliberkrav",
    "kaja_ajt": "Kaja",
    "kaja_ajf": "Jakttid",
    "kaja_klock": "Jakt under dygnet",
    "kaja_kalib": "Kaliberkrav",
    "kanadagas1": "Kanadagås",
    "kanadagas_": "Jakttid",
    "kanadaga_1": "Jakt under dygnet",
    "kanadaga_2": "Kaliberkrav",
    "knipa_ajt": "Knipa",
    "knipa_ajf": "Jakttid",
    "knipa_kloc": "Jakt under dygnet",
    "knipa_kali": "Kaliberkrav",
    "kricka_ajt": "Kricka",
    "kricka_ajf": "Jakttid",
    "kricka_klo": "Jakt under dygnet",
    "kricka_kal": "Kaliberkrav",
    "kraka_ajt": "Krake",
    "kraka_ajf": "Jakttid",
    "kraka_kloc": "Jakt under dygnet",
    "kraka_kali": "Kaliberkrav",
    "morkulla_1": "Morkulla",
    "morkulla_a": "Jakttid",
    "morkulla_k": "Jakt under dygnet",
    "morkulla_2": "Kaliberkrav",
    "notskrika1": "Nötskrika",
    "notskrika_": "Jakttid",
    "notskrik_1": "Jakt under dygnet",
    "notskrik_2": "Kaliberkrav",
    "orre_ajt": "Orre",
    "orre_ajf": "Jakttid",
    "orre_klock": "Jakt under dygnet",
    "orre_kalib": "Kaliberkrav",
    "orrtupp_in": "Orre Tupp",
    "orrtupp_aj": "Jakttid",
    "orrtupp_kl": "Jakt under dygnet",
    "orrtupp_ka": "Kaliberkrav",
    "rapphona_1": "Rapphöna",
    "rapphona_a": "Jakttid",
    "rapphona_k": "Jakt under dygnet",
    "rapphona_2": "Kaliberkrav",
    "ringduva_1": "Ringduva",
    "ringduva_a": "Jakttid",
    "ringduva_k": "Jakt under dygnet",
    "ringduva_2": "Kaliberkrav",
    "raka_info": "Råka",
    "raka_ajf": "Jakttid",
    "raka_klock": "Jakt under dygnet",
    "raka_kalib": "Kaliberkrav",
    "sjoorre__1": "Sjörre",
    "sjoorre_aj": "Jakttid",
    "sjoorre_kl": "Jakt under dygnet",
    "sjoorre_ka": "Kaliberkrav",
    "skata_ajt": "Skata",
    "skata_ajf": "Jakttid",
    "skata_kloc": "Jakt under dygnet",
    "skata_kali": "Kaliberkrav",
    "storkrake1": "Storskrake",
    "storkrake_": "Jakttid",
    "storkrak_1": "Jakt under dygnet",
    "storkrak_2": "Kaliberkrav",
    "tjader_ajt": "Tjäder",
    "tjader_ajf": "Jakttid",
    "tjader_klo": "Jakt under dygnet",
    "tjader_kal": "Kaliberkrav",
    "tjadertu_1": "Tjädertupp",
    "tjadertupp": "Jakttid",
    "tjadertu_2": "Jakt under dygnet",
    "tjadertu_3": "Kaliberkrav",
    "trana_ajt": "Trana",
    "trana_ajf": "Jakttid",
    "trana_klock": "Jakt under dygnet",
    "trana_kalib": "Kaliberkrav",
    "vigg_info": "Vigg",
    "vigg_ajf": "Jakttid",
    "vigg_klock": "Jakt under dygnet",
    "vigg_kalib": "Kaliberkrav"
};
